version:     "0018b--03-Aug-2021"
copyright:   "2021-2021"
description:
  OS 212 efsrdi
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Tips"
  link:      "/TIPS/"
- navbar:    "mylog"
  link:      "/TXT/mylog.txt"
- navbar:    "TarBall"
  link:      "/template.tar.bz2"
- navbar:    "GitHub"
  link:      "https://github.com/efsrdi/os212"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "About"
  link:      "/ABOUT/"
- navbar:    "GitHub Page"
  link:      "https://template.vlsm.org/"
title:       "GitHub Page Template"
lang:        "en-US"
author:      "J. Walker"
address:     "Box 7, Mawitaan, Bangalla."
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/efsrdi/os212"


